
defaultSemverRangePrefix: ''

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs


injectEnvironmentFiles:
    # With the introduction of yarn 4, we moved the npm token to the .env.yarn file. So the file itself is not optional during development. 
    # However, with the introduction of the .env.yarn file, the run of the renovate bot task failed because when using the yarn cli, 
    # yarn exited with an error because the file was missing. As we could not find a solution to add the file during the renovate 
    # bot task, we had to relax the condition and mark the .env.yarn file as optional with ? .
    # 
    # Note that the npm token from the .env.yarn file is already provided by the hostRule in the renovate.json configuration file, 
    # and is therefore not needed when running the renovate bot.
    - .env.yarn?

npmScopes:
    leistungserfassung:
        npmAuthToken: '${NPM_AUTH_TOKEN}'
        npmRegistryServer: 'https://gitlab.my-url.com/api/v4/packages/npm/'

plugins:
    - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
      path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
      spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'


